#ifndef BANKACCOUNTDEFINITION_READER_H
#define BANKACCOUNTDEFINITION_READER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct Account_table *Account_table_t;
typedef struct Account_table *Account_mutable_table_t;
typedef const flatbuffers_uoffset_t *Account_vec_t;
typedef flatbuffers_uoffset_t *Account_mutable_vec_t;
typedef const struct AccountInformation_table *AccountInformation_table_t;
typedef struct AccountInformation_table *AccountInformation_mutable_table_t;
typedef const flatbuffers_uoffset_t *AccountInformation_vec_t;
typedef flatbuffers_uoffset_t *AccountInformation_mutable_vec_t;
#ifndef Account_file_identifier
#define Account_file_identifier flatbuffers_identifier
#endif
/* deprecated, use Account_file_identifier */
#ifndef Account_identifier
#define Account_identifier flatbuffers_identifier
#endif
#define Account_type_hash ((flatbuffers_thash_t)0x59f8a2fc)
#define Account_type_identifier "\xfc\xa2\xf8\x59"
#ifndef AccountInformation_file_identifier
#define AccountInformation_file_identifier flatbuffers_identifier
#endif
/* deprecated, use AccountInformation_file_identifier */
#ifndef AccountInformation_identifier
#define AccountInformation_identifier flatbuffers_identifier
#endif
#define AccountInformation_type_hash ((flatbuffers_thash_t)0x24b40bca)
#define AccountInformation_type_identifier "\xca\x0b\xb4\x24"

typedef int8_t Status_enum_t;
__flatbuffers_define_integer_type(Status, Status_enum_t, 8)
#define Status_Open ((Status_enum_t)INT8_C(0))
#define Status_Closed ((Status_enum_t)INT8_C(1))
#define Status_Frozen ((Status_enum_t)INT8_C(2))

static inline const char *Status_name(Status_enum_t value)
{
    switch (value) {
    case Status_Open: return "Open";
    case Status_Closed: return "Closed";
    case Status_Frozen: return "Frozen";
    default: return "";
    }
}

static inline int Status_is_known_value(Status_enum_t value)
{
    switch (value) {
    case Status_Open: return 1;
    case Status_Closed: return 1;
    case Status_Frozen: return 1;
    default: return 0;
    }
}



struct Account_table { uint8_t unused__; };

static inline size_t Account_vec_len(Account_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Account_table_t Account_vec_at(Account_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Account_table_t, vec, i, 0)
__flatbuffers_table_as_root(Account)

__flatbuffers_define_scalar_field(0, Account, accountID, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(1, Account, balance, flatbuffers_float, float, 0.00000000f)
__flatbuffers_define_scalar_field(2, Account, interestRate, flatbuffers_double, double, 0.0000000000000000)
__flatbuffers_define_scalar_field(3, Account, accountStatus, Status, Status_enum_t, INT8_C(0))

struct AccountInformation_table { uint8_t unused__; };

static inline size_t AccountInformation_vec_len(AccountInformation_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AccountInformation_table_t AccountInformation_vec_at(AccountInformation_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AccountInformation_table_t, vec, i, 0)
__flatbuffers_table_as_root(AccountInformation)

__flatbuffers_define_string_field(0, AccountInformation, owner, 0)
__flatbuffers_define_scalar_field(1, AccountInformation, platinumRewards, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_vector_field(2, AccountInformation, accounts, Account_vec_t, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* BANKACCOUNTDEFINITION_READER_H */
