#ifndef BANKACCOUNTDEFINITION_VERIFIER_H
#define BANKACCOUNTDEFINITION_VERIFIER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef BANKACCOUNTDEFINITION_READER_H
#include "bankAccountDefinition_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int Account_verify_table(flatcc_table_verifier_descriptor_t *td);
static int AccountInformation_verify_table(flatcc_table_verifier_descriptor_t *td);

static int Account_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* accountID */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 4, 4) /* balance */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* interestRate */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 1, 1) /* accountStatus */)) return ret;
    return flatcc_verify_ok;
}

static inline int Account_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, Account_identifier, &Account_verify_table);
}

static inline int Account_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, Account_type_identifier, &Account_verify_table);
}

static inline int Account_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &Account_verify_table);
}

static inline int Account_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &Account_verify_table);
}

static int AccountInformation_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* owner */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 1, 1) /* platinumRewards */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 2, 0, &Account_verify_table) /* accounts */)) return ret;
    return flatcc_verify_ok;
}

static inline int AccountInformation_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, AccountInformation_identifier, &AccountInformation_verify_table);
}

static inline int AccountInformation_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, AccountInformation_type_identifier, &AccountInformation_verify_table);
}

static inline int AccountInformation_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &AccountInformation_verify_table);
}

static inline int AccountInformation_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &AccountInformation_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* BANKACCOUNTDEFINITION_VERIFIER_H */
