#ifndef BANK_ACCOUNT_READER_H
#define BANK_ACCOUNT_READER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct Savings_table *Savings_table_t;
typedef struct Savings_table *Savings_mutable_table_t;
typedef const flatbuffers_uoffset_t *Savings_vec_t;
typedef flatbuffers_uoffset_t *Savings_mutable_vec_t;
#ifndef Savings_file_identifier
#define Savings_file_identifier flatbuffers_identifier
#endif
/* deprecated, use Savings_file_identifier */
#ifndef Savings_identifier
#define Savings_identifier flatbuffers_identifier
#endif
#define Savings_type_hash ((flatbuffers_thash_t)0x3edeeb10)
#define Savings_type_identifier "\x10\xeb\xde\x3e"

typedef int8_t Status_enum_t;
__flatbuffers_define_integer_type(Status, Status_enum_t, 8)
#define Status_Open ((Status_enum_t)INT8_C(0))
#define Status_Closed ((Status_enum_t)INT8_C(1))
#define Status_Frozen ((Status_enum_t)INT8_C(2))

static inline const char *Status_name(Status_enum_t value)
{
    switch (value) {
    case Status_Open: return "Open";
    case Status_Closed: return "Closed";
    case Status_Frozen: return "Frozen";
    default: return "";
    }
}

static inline int Status_is_known_value(Status_enum_t value)
{
    switch (value) {
    case Status_Open: return 1;
    case Status_Closed: return 1;
    case Status_Frozen: return 1;
    default: return 0;
    }
}



struct Savings_table { uint8_t unused__; };

static inline size_t Savings_vec_len(Savings_vec_t vec)
__flatbuffers_vec_len(vec)
static inline Savings_table_t Savings_vec_at(Savings_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(Savings_table_t, vec, i, 0)
__flatbuffers_table_as_root(Savings)

__flatbuffers_define_scalar_field(0, Savings, accountID, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(1, Savings, balance, flatbuffers_int64, int64_t, INT64_C(0))
__flatbuffers_define_scalar_field(2, Savings, interestEarned, flatbuffers_double, double, 0.0000000000000000)
__flatbuffers_define_scalar_field(3, Savings, InterestRate, flatbuffers_double, double, 0.0000000000000000)


#include "flatcc/flatcc_epilogue.h"
#endif /* BANK_ACCOUNT_READER_H */
